# ==============================================
# Script created by Gurusekar for Evb0Rev
# Credit to Gurusekar for making this script.
# This script may NOT be resold or shared/claimed
# as your own work.
# ==============================================

command prison:
	permission: evb0.pro.tp
	cooldown: 60 seconds
	cooldown message: &cTry again later... %remaining time%
	trigger:
		teleport player to {location::prison}
		send "&eTeleported to Prison!" to player
		
command prison:setspawn:
	permission: op
	trigger:
		set {location::prison} to player's location
		
on region enter:
	if event-region is "prison":
		send title "&8&lWelcome to Prison" with subtitle "&7You must escape!"
		
on region enter:
	if event-region is "prison-exit":
		teleport player to {location::noob}
		
on portal enter:
	if region at player contains "prison-exit":
		cancel event
		teleport player to {location::noob}

# ==============================================
# Credits: Gurusekar
# This script may NOT be resold or shared/claimed
# as your own work.
# ==============================================
