# ==============================================
# Script created by Gurusekar for Evb0Rev
# Credit to Gurusekar for making this script.
# This script may NOT be resold or shared/claimed
# as your own work.
# ==============================================

on right click on iron bars:
	if region at event-block contains "helmet":
		teleport player to {location::helmet}
		
command setloc <text>:
	permission: op
	trigger:
		set {location::%arg-1%} to player's location
		send {location::%arg-1%} to player

# ==============================================
# Credits: Gurusekar
# This script may NOT be resold or shared/claimed
# as your own work.
# ==============================================
