# ==============================================
# Script created by Gurusekar for Evb0Rev
# Credit to Gurusekar for making this script.
# This script may NOT be resold or shared/claimed
# as your own work.
# ==============================================

command endurance:setspawn:
	permission: op
	trigger:
		set {location::endurance::start} to player's location
		
on region enter:
	if event-region is "enduranceenter":
		if {endurance::%uuid of player%} is not set:
			set {endurance::%uuid of player%} to true
			if player is sneaking:
				delete {endurance::%uuid of player%}
				remove slowness from player
				teleport player to {location::endurance::temple}
				send " "
				send "&2&lENDURANCE TEMPLE"
				send "&8----------------"
				send "You have entered the endurance temple. All players have been made invisible"
				send " "
				send title "&2&lEndurance Temple" with subtitle "&7Stay Strong"
				stop
			apply slowness 3 to player for 3 seconds
			wait 3 seconds
			{endurance::%uuid of player%} is set
			if region at player contains "enduranceenter":
				delete {endurance::%uuid of player%}
				remove slowness from player
				teleport player to {location::endurance::temple}
				send " "
				send "&2&lENDURANCE TEMPLE"
				send "&8----------------"
				send "You have entered the endurance temple. All players have been made invisible"
				send " "
				send title "&2&lEndurance Temple" with subtitle "&7Stay Strong"
			else:
				delete {endurance::%uuid of player%}
				
				
				
on sneak toggle:
	if region at player contains "enduranceenter":
		if {endurance::%uuid of player%} is set:				
			delete {endurance::%uuid of player%}
			remove slowness from player
			teleport player to {location::endurance::temple}
			send " "
			send "&2&lENDURANCE TEMPLE"
			send "&8----------------"
			send "You have entered the endurance temple. All players have been made invisible"
			send " "
			send title "&2&lEndurance Temple" with subtitle "&7Stay Strong"
			
on region enter:
	if event-region is "endurancedeath":
		set {fall::%uuid of player%} to true
		teleport player to {location::endurance::start}
		send title "&c&lEndurance Temple failed" with subtitle "&7You died!" to player
		wait 1 second
		delete {fall::%uuid of player%}
		
on region enter:
	if event-region is "enduranceend":
		apply slowness 5 to player for 3 seconds
		wait 3 second
		teleport player to {location::endurance::start}
		if {achievement::temple::endurance::%uuid of player%} is not set:
			set {achievement::temple::endurance::%uuid of player%} to true
			set {_t} to text component from "%player% has made achievement &a[Endurance Temple]"
			set hover event of {_t} to a new hover event showing "&aEndurance Temple &8- &aPass the Endurance Temple!"
			broadcast component {_t}

# ==============================================
# Credits: Gurusekar
# This script may NOT be resold or shared/claimed
# as your own work.
# ==============================================
