# ==============================================
# Script created by Gurusekar for Evb0Rev
# Credit to Gurusekar for making this script.
# This script may NOT be resold or shared/claimed
# as your own work.
# ==============================================

command momentum:setspawn:
	permission: op
	trigger:
		set {location::momentum::temple} to player's location
		
on region enter:
	if event-region is "momentumenter":
		if {momentum::%uuid of player%} is not set:
			set {momentum::%uuid of player%} to true
			if player is sneaking:
				delete {momentum::%uuid of player%}
				remove slowness from player
				teleport player to {location::momentum::temple}
				send " "
				send "&5&lMOMENTUM TEMPLE"
				send "&8----------------"
				send "You have entered the momentum temple. All players have been made invisible"
				send " "
				send title "&5&lMomentum Temple" with subtitle "&7Prepare yourself"
				stop
			apply slowness 3 to player for 3 seconds
			wait 3 seconds
			{momentum::%uuid of player%} is set
			if region at player contains "momentumenter":
				delete {momentum::%uuid of player%}
				remove slowness from player
				teleport player to {location::momentum::temple}
				send " "
				send "&5&lMOMENTUM TEMPLE"
				send "&8----------------"
				send "You have entered the momentum temple. All players have been made invisible"
				send " "
				send title "&5&lMomentum Temple" with subtitle "&7Prepare yourself"
			else:
				delete {momentum::%uuid of player%}
				
				
				
on sneak toggle:
	if region at player contains "momentumenter":
		if {momentum::%uuid of player%} is set:				
			delete {momentum::%uuid of player%}
			remove slowness from player
			teleport player to {location::momentum::temple}
			send " "
			send "&5&lMOMENTUM TEMPLE"
			send "&8----------------"
			send "You have entered the momentum temple. All players have been made invisible"
			send " "
			send title "&5&lMomentum Temple" with subtitle "&7Prepare yourself"
			
on region enter:
	if event-region is "momentumdeath":
		set {fall::%uuid of player%} to true
		teleport player to {location::momentum::start}
		send title "&c&lMomentum Temple failed" with subtitle "&7You died!" to player
		wait 1 second
		delete {fall::%uuid of player%}
		
on region enter:
	if event-region is "momentumend":
		apply slowness 5 to player for 3 seconds
		wait 3 second
		teleport player to {location::momentum::start}
		if {achievement::temple::momentum::%uuid of player%} is not set:
			set {achievement::temple::momentum::%uuid of player%} to true
			set {_t} to text component from "%player% has made achievement &a[Momentum Temple]"
			set hover event of {_t} to a new hover event showing "&aMomentum Temple &8- &aPass the Momentum Temple!"
			broadcast component {_t}

# ==============================================
# Credits: Gurusekar
# This script may NOT be resold or shared/claimed
# as your own work.
# ==============================================
