# ==============================================
# Script created by Gurusekar for Evb0Rev
# Credit to Gurusekar for making this script.
# This script may NOT be resold or shared/claimed
# as your own work.
# ==============================================

command pro:
	permission: evb0.pro.tp
	cooldown: 60 seconds
	cooldown message: &cTry again later... %remaining time%
	trigger:
		teleport player to {location::pro}
		send "&eTeleported to Pro level!" to player
		
#command pro:setspawn:
#	permission: op
#	trigger:
#		set {location::pro} to player's location

# ==============================================
# Credits: Gurusekar
# This script may NOT be resold or shared/claimed
# as your own work.
# ==============================================
